# Site
name: "ChronoRank"
title: "ChronoRank"
description: "Relojes, horologia, Chrono, Rolex, Tudor, Omega"
logo: 'https://chronorank.com/images/chronorank_240.png'
favicon: 'images/favico.png'
baseurl: /
google_analytics: 'UA-50598012-1'
disqus: ''
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  oscar:
    name: Oscar Valenzuela
    display_name: Oscar V.
    gravatar: e17523fd9dfc61bcdd837836bfc8fa21
    email: avatarchronorank.g5xwu@passmail.net
    web: https://www.ovalenzuela.com
    twitter: 
    linkedin: https://www.linkedin.com/in/alkamod/
    description: "Coleccionista de relojes de pulsera mec&aacute;nicos, amante de la m&uacute;sica jazz y techno, y entusiasta de la tecnolog&iacute;a."
  chronorank:
    name: ChronoRank
    display_name: Editorial
    gravatar: cc3d3888f617553b2e60609ffa7ea86e
    email: avatarchronorank.g5xwu@passmail.net
    web: https://www.chronorank.com
    twitter: 
    linkedin: 
    description: "Blog sobre relojes inspirado en la comunidad y potenciado con AI. Combinamos tecnolog&iacute;a y pasi&oacute;n relojera para ofrecer contenido &uacute;nico sobre horolog&iacute;a, historia y estilo."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
